language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5
    - android-sdk-license-c81a61d9
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk: oraclejdk8

install:
  - true

script:
  - ./gradlew clean build check

cache:
  directories:
    - $HOME/.m2